-- Multi-tenant baseline: sites registry
CREATE TABLE IF NOT EXISTS sites (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug            VARCHAR(100) NOT NULL UNIQUE,
    name            VARCHAR(255) NOT NULL,
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS site_config (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id         BIGINT NOT NULL,
    config_key      VARCHAR(100) NOT NULL,
    config_value    TEXT NOT NULL,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_site_config_site_key UNIQUE (site_id, config_key),
    CONSTRAINT fk_site_config_site FOREIGN KEY (site_id) REFERENCES sites(id)
);

CREATE TABLE IF NOT EXISTS memories (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id         BIGINT NOT NULL,
    title           VARCHAR(200) NOT NULL,
    message         TEXT NOT NULL,
    memory_date     DATE,
    location        VARCHAR(200),
    image_url       VARCHAR(500) NOT NULL,
    display_order   INT NOT NULL DEFAULT 0,
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_memories_site FOREIGN KEY (site_id) REFERENCES sites(id)
);

CREATE TABLE IF NOT EXISTS photos (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id         BIGINT NOT NULL,
    title           VARCHAR(200),
    caption         TEXT,
    image_url       VARCHAR(500) NOT NULL,
    memory_id       BIGINT,
    display_order   INT NOT NULL DEFAULT 0,
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_photos_site FOREIGN KEY (site_id) REFERENCES sites(id),
    CONSTRAINT fk_photos_memory FOREIGN KEY (memory_id) REFERENCES memories(id)
);

CREATE TABLE IF NOT EXISTS quotes (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id         BIGINT NOT NULL,
    text            TEXT NOT NULL,
    author          VARCHAR(200),
    display_order   INT NOT NULL DEFAULT 0,
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_quotes_site FOREIGN KEY (site_id) REFERENCES sites(id)
);

CREATE TABLE IF NOT EXISTS love_bombs (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id         BIGINT NOT NULL,
    message         TEXT NOT NULL,
    display_order   INT NOT NULL DEFAULT 0,
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_love_bombs_site FOREIGN KEY (site_id) REFERENCES sites(id)
);

CREATE TABLE IF NOT EXISTS reasons (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id         BIGINT NOT NULL,
    short_label     VARCHAR(100) NOT NULL,
    long_message    TEXT NOT NULL,
    display_order   INT NOT NULL DEFAULT 0,
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_reasons_site FOREIGN KEY (site_id) REFERENCES sites(id)
);

CREATE TABLE IF NOT EXISTS open_when_messages (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id         BIGINT NOT NULL,
    envelope_label  VARCHAR(200) NOT NULL,
    message         TEXT NOT NULL,
    display_order   INT NOT NULL DEFAULT 0,
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_open_when_site FOREIGN KEY (site_id) REFERENCES sites(id)
);

CREATE TABLE IF NOT EXISTS love_bomb_history (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id         BIGINT NOT NULL,
    session_id      VARCHAR(64) NOT NULL,
    love_bomb_id    BIGINT NOT NULL,
    shown_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_love_bomb_history_site FOREIGN KEY (site_id) REFERENCES sites(id),
    CONSTRAINT fk_love_bomb_history_bomb FOREIGN KEY (love_bomb_id) REFERENCES love_bombs(id)
);

CREATE INDEX IF NOT EXISTS idx_memories_site_active_order ON memories(site_id, active, display_order);
CREATE INDEX IF NOT EXISTS idx_photos_site_active_order ON photos(site_id, active, display_order);
CREATE INDEX IF NOT EXISTS idx_quotes_site_active_order ON quotes(site_id, active, display_order);
CREATE INDEX IF NOT EXISTS idx_love_bombs_site_active ON love_bombs(site_id, active);
CREATE INDEX IF NOT EXISTS idx_reasons_site_active_order ON reasons(site_id, active, display_order);
CREATE INDEX IF NOT EXISTS idx_open_when_site_active_order ON open_when_messages(site_id, active, display_order);
CREATE INDEX IF NOT EXISTS idx_love_bomb_history_site_session ON love_bomb_history(site_id, session_id, shown_at);
