CREATE TABLE IF NOT EXISTS site_config (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_key      VARCHAR(100) NOT NULL UNIQUE,
    config_value    TEXT NOT NULL,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS memories (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title           VARCHAR(200) NOT NULL,
    message         TEXT NOT NULL,
    memory_date     DATE,
    location        VARCHAR(200),
    image_url       VARCHAR(500) NOT NULL,
    display_order   INT NOT NULL DEFAULT 0,
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS photos (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title           VARCHAR(200),
    caption         TEXT,
    image_url       VARCHAR(500) NOT NULL,
    display_order   INT NOT NULL DEFAULT 0,
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS quotes (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text            TEXT NOT NULL,
    author          VARCHAR(200),
    display_order   INT NOT NULL DEFAULT 0,
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS love_bombs (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message         TEXT NOT NULL,
    display_order   INT NOT NULL DEFAULT 0,
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS reasons (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    short_label     VARCHAR(100) NOT NULL,
    long_message    TEXT NOT NULL,
    display_order   INT NOT NULL DEFAULT 0,
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS open_when_messages (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    envelope_label  VARCHAR(200) NOT NULL,
    message         TEXT NOT NULL,
    display_order   INT NOT NULL DEFAULT 0,
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS love_bomb_history (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id      VARCHAR(64) NOT NULL,
    love_bomb_id    BIGINT NOT NULL,
    shown_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_love_bomb_history_bomb FOREIGN KEY (love_bomb_id) REFERENCES love_bombs(id)
);

CREATE INDEX IF NOT EXISTS idx_memories_active_order ON memories(active, display_order);
CREATE INDEX IF NOT EXISTS idx_photos_active_order ON photos(active, display_order);
CREATE INDEX IF NOT EXISTS idx_quotes_active_order ON quotes(active, display_order);
CREATE INDEX IF NOT EXISTS idx_love_bombs_active ON love_bombs(active);
CREATE INDEX IF NOT EXISTS idx_reasons_active_order ON reasons(active, display_order);
CREATE INDEX IF NOT EXISTS idx_open_when_active_order ON open_when_messages(active, display_order);
CREATE INDEX IF NOT EXISTS idx_love_bomb_history_session ON love_bomb_history(session_id, shown_at);
